name: Python Tests and Linting
on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"

      - name: Run Ruff (linter)
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest -v

      - name: Check code complexity
        run: uv run radon cc Contact_Manager -s -a > radon_report.txt

      - name: Publish Radon summary
        run: |
          # Extraer promedio (Average)
          AVG=$(grep "Average" radon_report.txt | awk '{print $2}')
          echo "### Radon Complexity Report" >> $GITHUB_STEP_SUMMARY
          echo "- Average cyclomatic complexity: $AVG" >> $GITHUB_STEP_SUMMARY